Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ../dataset\cifar-10\cifar-10-python.tar.gz
100%|█████████████████████████████████████████████████████████████| 170M/170M [00:13<00:00, 13.0MB/s]
Extracting ../dataset\cifar-10\cifar-10-python.tar.gz to ../dataset\cifar-10
Files already downloaded and verified
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name    | Type             | Params | Mode
-----------------------------------------------------
0 | model   | Sequential       | 1.7 M  | train
1 | loss_fn | CrossEntropyLoss | 0      | train
-----------------------------------------------------
1.7 M     Trainable params
0         Non-trainable params
1.7 M     Total params
6.829     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
Sanity Checking: |                                                             | 0/? [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\junun\documents\aiclass\main.py", line 207, in <module>
    main(args.model, args.dataset, args.data, args.batch, args.epoch, args.save,
  File "C:\Users\junun\documents\aiclass\main.py", line 152, in main
    trainer.fit(model, datamodule)
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\trainer\call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 981, in _run
    results = self._run_stage()
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1023, in _run_stage
    self._run_sanity_check()
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1052, in _run_sanity_check
    val_loop.run()
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\loops\utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 110, in run
    self.setup_data()
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 166, in setup_data
    dataloaders = _request_dataloader(source)
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py", line 325, in _request_dataloader
    return data_source.dataloader()
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py", line 292, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
  File "C:\Users\junun\miniconda3\envs\imagenet\lib\site-packages\lightning\pytorch\trainer\call.py", line 189, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "C:\Users\junun\documents\aiclass\src\dataset.py", line 80, in val_dataloader
    batch_size=self.batch_size_per_device,
AttributeError: 'CustomDataModule' object has no attribute 'batch_size_per_device'
